//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CherryUpdater {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CherryUpdater.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updatefout.
        /// </summary>
        internal static string CptActivityFailed {
            get {
                return ResourceManager.GetString("CptActivityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instellingen.
        /// </summary>
        internal static string CptConfigurationDialog {
            get {
                return ResourceManager.GetString("CptConfigurationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestig afbreken.
        /// </summary>
        internal static string CptConfirmAbortQuestion {
            get {
                return ResourceManager.GetString("CptConfirmAbortQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindingsfout.
        /// </summary>
        internal static string CptConnectionError {
            get {
                return ResourceManager.GetString("CptConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mede mogelijk gemaakt door....
        /// </summary>
        internal static string CptCreditsNameList {
            get {
                return ResourceManager.GetString("CptCreditsNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installatieprogramma beëindigd.
        /// </summary>
        internal static string CptDriverInstallationFinished {
            get {
                return ResourceManager.GetString("CptDriverInstallationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan CherryUpdater niet starten.
        /// </summary>
        internal static string CptEnvironmentNotSane {
            get {
                return ResourceManager.GetString("CptEnvironmentNotSane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparaattype niet herkend.
        /// </summary>
        internal static string CptIncompatibleProductModel {
            get {
                return ResourceManager.GetString("CptIncompatibleProductModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultaat opvraging.
        /// </summary>
        internal static string CptQueryCompleted {
            get {
                return ResourceManager.GetString("CptQueryCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opvraagfout.
        /// </summary>
        internal static string CptQueryFailed {
            get {
                return ResourceManager.GetString("CptQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kritieke programmafout.
        /// </summary>
        internal static string CptUnhandledProgramError {
            get {
                return ResourceManager.GetString("CptUnhandledProgramError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Afbreken.
        /// </summary>
        internal static string LblAbortButton {
            get {
                return ResourceManager.GetString("LblAbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanpassen permissies afgerond.
        /// </summary>
        internal static string LblActivityAdapChangePermissionsFinished {
            get {
                return ResourceManager.GetString("LblActivityAdapChangePermissionsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanpassen permissie van bestand {0}....
        /// </summary>
        internal static string LblActivityAdaptChangePermission {
            get {
                return ResourceManager.GetString("LblActivityAdaptChangePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installeren afgerond.
        /// </summary>
        internal static string LblActivityInstallFinished {
            get {
                return ResourceManager.GetString("LblActivityInstallFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installeren van pakket {0}....
        /// </summary>
        internal static string LblActivityInstallPackage {
            get {
                return ResourceManager.GetString("LblActivityInstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaatsen van bestand {0}....
        /// </summary>
        internal static string LblActivityPushFile {
            get {
                return ResourceManager.GetString("LblActivityPushFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaatsen van bestanden....
        /// </summary>
        internal static string LblActivityPushFiles {
            get {
                return ResourceManager.GetString("LblActivityPushFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaatsen afgerond.
        /// </summary>
        internal static string LblActivityPushFinished {
            get {
                return ResourceManager.GetString("LblActivityPushFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Terug.
        /// </summary>
        internal static string LblBackButton {
            get {
                return ResourceManager.GetString("LblBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Annuleren.
        /// </summary>
        internal static string LblCancelButton {
            get {
                return ResourceManager.GetString("LblCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druk op Start om te beginnen.
        /// </summary>
        internal static string LblClickToStart {
            get {
                return ResourceManager.GetString("LblClickToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;luiten.
        /// </summary>
        internal static string LblCloseButton {
            get {
                return ResourceManager.GetString("LblCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logbestand maken:.
        /// </summary>
        internal static string LblEnableLogging {
            get {
                return ResourceManager.GetString("LblEnableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitvoering beeindigd..
        /// </summary>
        internal static string LblExecutionNotSuccessful {
            get {
                return ResourceManager.GetString("LblExecutionNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitvoering succesvol afgerond..
        /// </summary>
        internal static string LblExecutionSuccessful {
            get {
                return ResourceManager.GetString("LblExecutionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negeer producttype.
        /// </summary>
        internal static string LblIgnoreProductModel {
            get {
                return ResourceManager.GetString("LblIgnoreProductModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string LblLogGroupBox {
            get {
                return ResourceManager.GetString("LblLogGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foutmeldingen.
        /// </summary>
        internal static string LblLogLevelError {
            get {
                return ResourceManager.GetString("LblLogLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uitgebreid.
        /// </summary>
        internal static string LblLogLevelVerbose {
            get {
                return ResourceManager.GetString("LblLogLevelVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waarschuwingen.
        /// </summary>
        internal static string LblLogLevelWarn {
            get {
                return ResourceManager.GetString("LblLogLevelWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naar menu.
        /// </summary>
        internal static string LblMenuButton {
            get {
                return ResourceManager.GetString("LblMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string LblOkButton {
            get {
                return ResourceManager.GetString("LblOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opvragen.
        /// </summary>
        internal static string LblQueryButton {
            get {
                return ResourceManager.GetString("LblQueryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot van tablet afgerond.
        /// </summary>
        internal static string LblRebootFinished {
            get {
                return ResourceManager.GetString("LblRebootFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon ballonnen met helptekst.
        /// </summary>
        internal static string LblShowHelp {
            get {
                return ResourceManager.GetString("LblShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mogelijk dankzij het werk van diverse forumleden.
        /// </summary>
        internal static string LblSplashCredits1 {
            get {
                return ResourceManager.GetString("LblSplashCredits1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains a modified version of MAD Bee by camalot.
        /// </summary>
        internal static string LblSplashCredits2 {
            get {
                return ResourceManager.GetString("LblSplashCredits2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruik geheel op eigen risico!.
        /// </summary>
        internal static string LblSplashDisclaimer {
            get {
                return ResourceManager.GetString("LblSplashDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met initialiseren ADB....
        /// </summary>
        internal static string LblSplashInitializing {
            get {
                return ResourceManager.GetString("LblSplashInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versie {0}.
        /// </summary>
        internal static string LblSplashVersion {
            get {
                return ResourceManager.GetString("LblSplashVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Start.
        /// </summary>
        internal static string LblStartButton {
            get {
                return ResourceManager.GetString("LblStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met toepassen van instellingen. Dit kan enkele seconden duren....
        /// </summary>
        internal static string LblStatusApplyingSettings {
            get {
                return ResourceManager.GetString("LblStatusApplyingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LblStatusGroupBox {
            get {
                return ResourceManager.GetString("LblStatusGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meerdere apparaten verbonden.
        /// </summary>
        internal static string LblStatusMoreDevices {
            get {
                return ResourceManager.GetString("LblStatusMoreDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen apparaat verbonden.
        /// </summary>
        internal static string LblStatusNoDevices {
            get {
                return ResourceManager.GetString("LblStatusNoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbonden apparaat: {0}.
        /// </summary>
        internal static string LblStatusOneDevice {
            get {
                return ResourceManager.GetString("LblStatusOneDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbonden apparaat: {0} (niet online).
        /// </summary>
        internal static string LblStatusOneDeviceNotOnline {
            get {
                return ResourceManager.GetString("LblStatusOneDeviceNotOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen apparaatgegevens beschikbaar.
        /// </summary>
        internal static string LblStatusUnknown {
            get {
                return ResourceManager.GetString("LblStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type onbekend.
        /// </summary>
        internal static string LblStatusUnknownModel {
            get {
                return ResourceManager.GetString("LblStatusUnknownModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitvoeren.
        /// </summary>
        internal static string LblTaskButton {
            get {
                return ResourceManager.GetString("LblTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met {0}....
        /// </summary>
        internal static string LblTaskExecution {
            get {
                return ResourceManager.GetString("LblTaskExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruik adb.exe voor uitvoeren opdrachten.
        /// </summary>
        internal static string LblUseAdbProvider {
            get {
                return ResourceManager.GetString("LblUseAdbProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wacht op reboot van het tablet....
        /// </summary>
        internal static string LblWaitForReboot {
            get {
                return ResourceManager.GetString("LblWaitForReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In&amp;fo.
        /// </summary>
        internal static string MnuAbout {
            get {
                return ResourceManager.GetString("MnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Instellingen.
        /// </summary>
        internal static string MnuConfiguration {
            get {
                return ResourceManager.GetString("MnuConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanpassen permissies.
        /// </summary>
        internal static string MsgActivityAdaptChangePermissions {
            get {
                return ResourceManager.GetString("MsgActivityAdaptChangePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaatsen bestand.
        /// </summary>
        internal static string MsgActivityAdaptPushFile {
            get {
                return ResourceManager.GetString("MsgActivityAdaptPushFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaatsen bestanden.
        /// </summary>
        internal static string MsgActivityAdaptPushFiles {
            get {
                return ResourceManager.GetString("MsgActivityAdaptPushFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Stap mislukt: {0}.
        /// </summary>
        internal static string MsgActivityCompletedFailure {
            get {
                return ResourceManager.GetString("MsgActivityCompletedFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Stap geslaagd.
        /// </summary>
        internal static string MsgActivityCompletedSuccess {
            get {
                return ResourceManager.GetString("MsgActivityCompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De technische fout is van type {0} met boodschap: {1}
        ///.
        /// </summary>
        internal static string MsgActivityExceptionOccured {
            get {
                return ResourceManager.GetString("MsgActivityExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een fout opgetreden bij het uitvoeren van de update..
        /// </summary>
        internal static string MsgActivityFailed {
            get {
                return ResourceManager.GetString("MsgActivityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Stap {0} van {1} overgeslagen: onjuist aantal parameters ({3}) voor opdracht {2}.
        ///Opdrachtregel: {4}.
        /// </summary>
        internal static string MsgActivitySkipped {
            get {
                return ResourceManager.GetString("MsgActivitySkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Stap {0} van {1}: {2}.
        /// </summary>
        internal static string MsgActivityStart {
            get {
                return ResourceManager.GetString("MsgActivityStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vervangen bestand {1}\{2}.
        /// </summary>
        internal static string MsgActivityStartAdapt {
            get {
                return ResourceManager.GetString("MsgActivityStartAdapt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vervangen bestanden {1}\{2}.
        /// </summary>
        internal static string MsgActivityStartAdaptdir {
            get {
                return ResourceManager.GetString("MsgActivityStartAdaptdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to installeren pakket {1}.
        /// </summary>
        internal static string MsgActivityStartInstall {
            get {
                return ResourceManager.GetString("MsgActivityStartInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to installeren pakketten {1}\{2}.
        /// </summary>
        internal static string MsgActivityStartInstalldir {
            get {
                return ResourceManager.GetString("MsgActivityStartInstalldir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stoppen ADB serverproces.
        /// </summary>
        internal static string MsgActivityStartKillServer {
            get {
                return ResourceManager.GetString("MsgActivityStartKillServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plaatsen bestand {1}.
        /// </summary>
        internal static string MsgActivityStartPush {
            get {
                return ResourceManager.GetString("MsgActivityStartPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plaatsen bestanden {1}\{2}.
        /// </summary>
        internal static string MsgActivityStartPushdir {
            get {
                return ResourceManager.GetString("MsgActivityStartPushdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to herstarten tablet.
        /// </summary>
        internal static string MsgActivityStartReboot {
            get {
                return ResourceManager.GetString("MsgActivityStartReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to herkoppelen bestandssysteem.
        /// </summary>
        internal static string MsgActivityStartRemount {
            get {
                return ResourceManager.GetString("MsgActivityStartRemount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uitvoeren commando &apos;{0}&apos;.
        /// </summary>
        internal static string MsgActivityStartShell {
            get {
                return ResourceManager.GetString("MsgActivityStartShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uitvoeren opdracht.
        /// </summary>
        internal static string MsgActivityStartUnknown {
            get {
                return ResourceManager.GetString("MsgActivityStartUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to controleren verbinding.
        /// </summary>
        internal static string MsgActivityStartVerify {
            get {
                return ResourceManager.GetString("MsgActivityStartVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een fout opgetreden bij het uitvoeren van het ADB programma. Verzeker u ervan dat er een juiste, werkende versie van het ADB programma beschikbaar is..
        /// </summary>
        internal static string MsgAdbError {
            get {
                return ResourceManager.GetString("MsgAdbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to het ADB programma (&quot;{0}&quot;) bestaat niet.
        /// </summary>
        internal static string MsgADBNotFound {
            get {
                return ResourceManager.GetString("MsgADBNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan het ADB programma niet draaien. Verzeker u ervan dat het ZIP-bestand met dit programma volledig is uitgepakt..
        /// </summary>
        internal static string MsgCannotRun {
            get {
                return ResourceManager.GetString("MsgCannotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan de bestanden binnen de map niet opvragen.
        /// </summary>
        internal static string MsgCantLoadDirectoryFiles {
            get {
                return ResourceManager.GetString("MsgCantLoadDirectoryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to het configuratiebestand (&quot;{0}&quot;) bestaat niet.
        /// </summary>
        internal static string MsgCommandsFileNotFound {
            get {
                return ResourceManager.GetString("MsgCommandsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u wilt afbreken?.
        /// </summary>
        internal static string MsgConfirmAbortQuestion {
            get {
                return ResourceManager.GetString("MsgConfirmAbortQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CherryUpdater had niet tot stand kunnen komen zonder het fundament, de inspiratie, de bijdragen, het meedenken en het testen van ChemoNL, Den Eds, Gerard, JoJo, josgp, Lessram, visseronline en alle anderen die ik hier vergeten ben te noemen..
        /// </summary>
        internal static string MsgCreditsNameList {
            get {
                return ResourceManager.GetString("MsgCreditsNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daar bovenop is er een fout van type {0} opgetreden bij het wegschrijven van de foutbeschrijving, met boodschap: {1}
        ///Merk dit alstublieft op bij het melden van de fout..
        /// </summary>
        internal static string MsgDetailErrorLogException {
            get {
                return ResourceManager.GetString("MsgDetailErrorLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een gedetailleerde foutbeschrijving weggeschreven in het volgende bestand: {0}.
        ///Stuur deze alstublieft mee bij het melden van de fout..
        /// </summary>
        internal static string MsgDetailErrorLogWritten {
            get {
                return ResourceManager.GetString("MsgDetailErrorLogWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het installatieprogramma van de ADB drivers is afgerond. Wilt u de verbinding nogmaals testen?.
        /// </summary>
        internal static string MsgDriverInstallationFinished {
            get {
                return ResourceManager.GetString("MsgDriverInstallationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CherryUpdater kan niet starten om de volgende reden: {0}. Herstel het probleem en start CherryUpdater opnieuw..
        /// </summary>
        internal static string MsgEnvironmentNotSane {
            get {
                return ResourceManager.GetString("MsgEnvironmentNotSane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het spijt me, het lijkt erop dat er een kritieke fout is opgetreden in CherryUpdater.
        ///Er is een niet afgehandelde fout opgetreden van type {0}, met boodschap: {1}
        ///.
        /// </summary>
        internal static string MsgFatalErrorOccured {
            get {
                return ResourceManager.GetString("MsgFatalErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het type van het verbonden Android apparaat wordt niet herkend door CherryUpdater. Als het apparaat niet van een ondersteund type is en updates toch worden toegepast, dan kan dit problemen veroorzaken in de werking van het apparaat..
        /// </summary>
        internal static string MsgIncompatibleProductModel {
            get {
                return ResourceManager.GetString("MsgIncompatibleProductModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilt u de ADB drivers nu installeren?.
        /// </summary>
        internal static string MsgInstallDriverQuestion {
            get {
                return ResourceManager.GetString("MsgInstallDriverQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het gekoppelde Android apparaat is niet in de juiste modus. Deze kan bijvoorbeeld in recoverymodus gestart zijn..
        /// </summary>
        internal static string MsgInvalidState {
            get {
                return ResourceManager.GetString("MsgInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is meer dan één Android apparaat gevonden. Zorg ervoor dat maar één Cherry tablet op de PC is aangesloten..
        /// </summary>
        internal static string MsgMoreDevices {
            get {
                return ResourceManager.GetString("MsgMoreDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is geen Android apparaat gevonden. Verzeker u ervan dat:
        ///- de ADB drivers geïnstalleerd zijn 
        ///- het tablet met de USB kabel is aangesloten op de PC 
        ///- het tablet in USB debug modus staat
        ///- een geïnstalleerde firewall netwerkcommunicatie tussen CherryUpdater en adb.exe (TCP poort 5037) niet blokkeert.
        /// </summary>
        internal static string MsgNoDevices {
            get {
                return ResourceManager.GetString("MsgNoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op het gekoppelde Android apparaat kunnen geen wijzigingen worden doorgevoerd. Waarschijnlijk is een ander apparaat dan een Cherry tablet aangesloten..
        /// </summary>
        internal static string MsgNoRoot {
            get {
                return ResourceManager.GetString("MsgNoRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een fout opgetreden bij het opvragen..
        /// </summary>
        internal static string MsgQueryFailed {
            get {
                return ResourceManager.GetString("MsgQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///Wilt u dit resultaat op het klembord zetten?.
        /// </summary>
        internal static string MsgQueryOfferClipboardCopy {
            get {
                return ResourceManager.GetString("MsgQueryOfferClipboardCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een verbindingsfout opgetreden met het tablet..
        /// </summary>
        internal static string MsgSyncResultConnectionError {
            get {
                return ResourceManager.GetString("MsgSyncResultConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een fout opgetreden bij het lezen van het bestand..
        /// </summary>
        internal static string MsgSyncResultFileReadError {
            get {
                return ResourceManager.GetString("MsgSyncResultFileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een fout opgetreden bij het schrijven van het bestand..
        /// </summary>
        internal static string MsgSyncResultFileWriteError {
            get {
                return ResourceManager.GetString("MsgSyncResultFileWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het lokale pad wijst naar een directory/map..
        /// </summary>
        internal static string MsgSyncResultLocalIsDirectory {
            get {
                return ResourceManager.GetString("MsgSyncResultLocalIsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De doeldirectory/map bestaat niet..
        /// </summary>
        internal static string MsgSyncResultNoDirTarget {
            get {
                return ResourceManager.GetString("MsgSyncResultNoDirTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het te plaatsen bestand bestaat niet..
        /// </summary>
        internal static string MsgSyncResultNoLocalFile {
            get {
                return ResourceManager.GetString("MsgSyncResultNoLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het object op het tablet bestaat niet..
        /// </summary>
        internal static string MsgSyncResultNoRemoteObject {
            get {
                return ResourceManager.GetString("MsgSyncResultNoRemoteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het pad op het tablet wijst naar een bestand..
        /// </summary>
        internal static string MsgSyncResultRemoteIsFile {
            get {
                return ResourceManager.GetString("MsgSyncResultRemoteIsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De tekenset wordt niet ondersteund voor het pad op het tablet..
        /// </summary>
        internal static string MsgSyncResultRemotePathEncoding {
            get {
                return ResourceManager.GetString("MsgSyncResultRemotePathEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het pad op het tablet is te lang..
        /// </summary>
        internal static string MsgSyncResultRemotePathLength {
            get {
                return ResourceManager.GetString("MsgSyncResultRemotePathLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het doelpad wijst naar een bestand..
        /// </summary>
        internal static string MsgSyncResultTargetIsFile {
            get {
                return ResourceManager.GetString("MsgSyncResultTargetIsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een onbekende fout opgetreden..
        /// </summary>
        internal static string MsgSyncResultUnknownError {
            get {
                return ResourceManager.GetString("MsgSyncResultUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er kon geen werkende verbinding met het Cherry tablet worden opgezet..
        /// </summary>
        internal static string MsgVerifyFailed {
            get {
                return ResourceManager.GetString("MsgVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitzondering bij uitvoeren activiteit, type {0}: {1}.
        /// </summary>
        internal static string TxtActivityException {
            get {
                return ResourceManager.GetString("TxtActivityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Uitzonderingsgegevens:.
        /// </summary>
        internal static string TxtExceptionData {
            get {
                return ResourceManager.GetString("TxtExceptionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Bevat uitzondering: {0}.
        /// </summary>
        internal static string TxtInnerException {
            get {
                return ResourceManager.GetString("TxtInnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Stack trace: {0}.
        /// </summary>
        internal static string TxtStackTrace {
            get {
                return ResourceManager.GetString("TxtStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niet-verwerkte uitzondering {0}: {1}.
        /// </summary>
        internal static string TxtUnhandledException {
            get {
                return ResourceManager.GetString("TxtUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;     
        ///	targetNamespace=&quot;http://schema.vanbergen.local/Tools/CherryUpdater/CommandFile&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    attributeFormDefault=&quot;unqualified&quot;
        ///    xmlns=&quot;http://schema.vanbergen.local/Tools/CherryUpdater/CommandFile&quot;
        ///    xmlns:dbda=&quot;http://schema.vanbergen.local/Tools/CherryUpdater/CommandFile&quot;
        ///&gt;
        ///  &lt;xs:simpleType name=&quot;requirePathType&quot;&gt;
        ///    &lt;xs:restriction base=&quot;xs:string&quot;&gt;
        ///      &lt;xs:enum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XsdCommandFile {
            get {
                return ResourceManager.GetString("XsdCommandFile", resourceCulture);
            }
        }
    }
}
